create table inscripciones(
    id number(3),
    usuario varchar2(25),
    curso varchar2(25),
    fecha_inscripcion date,
    precio number(5),
    pais varchar2(25)
);


INSERT ALL
    INTO INSCRIPCIONES(ID,USUARIO,CURSO,FECHA_INSCRIPCION,PRECIO,PAIS) VALUES (1,'Ana','SQL Básico',TO_DATE('2026/01/10', 'YYYY/MM/DD'),100,'CO')
    INTO INSCRIPCIONES(ID,USUARIO,CURSO,FECHA_INSCRIPCION,PRECIO,PAIS) VALUES (2,'Luis','Python',TO_DATE('2026/01/10', 'YYYY/MM/DD'),120,'CO')
    INTO INSCRIPCIONES(ID,USUARIO,CURSO,FECHA_INSCRIPCION,PRECIO,PAIS) VALUES (3,'Ana','Python',TO_DATE('2026/01/15', 'YYYY/MM/DD'),120,'MX')
    INTO INSCRIPCIONES(ID,USUARIO,CURSO,FECHA_INSCRIPCION,PRECIO,PAIS) VALUES (4,'Maria','SQL Básico',TO_DATE('2026/01/15', 'YYYY/MM/DD'),100,'CO')
    INTO INSCRIPCIONES(ID,USUARIO,CURSO,FECHA_INSCRIPCION,PRECIO,PAIS) VALUES (5,'Luis','Big Data',TO_DATE('2026/01/20', 'YYYY/MM/DD'),200,'CO')
    INTO INSCRIPCIONES(ID,USUARIO,CURSO,FECHA_INSCRIPCION,PRECIO,PAIS) VALUES (6,'Carlos','SQL Básico',TO_DATE('2026/01/20', 'YYYY/MM/DD'),100,'')
SELECT * FROM DUAL;
					
SELECT
    NVL(PAIS, 'DESCONOCIDO') AS PAIS
FROM INSCRIPCIONES;

SELECT * FROM INSCRIPCIONES;


select curso, sum(precio)
from inscripciones
group by curso;

select NVL(pais, 'DESCONOCIDO') AS PAIS, sum(precio)
from inscripciones
group by pais;

SELECT CURSO, SUM(PRECIO) AS PRECIO_MAYOR , COUNT(*) AS CANTIDAD_INSCRIPCIONES
FROM INSCRIPCIONES
GROUP BY CURSO
ORDER BY CANTIDAD_INSCRIPCIONES DESC
FETCH FIRST 1 ROW ONLY;

SELECT USUARIO, SUM(PRECIO) AS GASTO
FROM INSCRIPCIONES
GROUP BY USUARIO
ORDER BY GASTO DESC
FETCH FIRST 1 ROW ONLY;

SELECT FECHA_INSCRIPCION, SUM(PRECIO) AS INGRESOS
FROM INSCRIPCIONES
GROUP BY FECHA_INSCRIPCION
ORDER BY INGRESOS DESC
FETCH FIRST 1 ROW ONLY;


DROP TABLE INSCRIPCIONES;